# Generated by Django 2.1 on 2022-07-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sssss',
            new_name='image',
        ),
    ]
